return {
  char_highlight_list = {
    "IndentBlanklineIndent1",
    "IndentBlanklineIndent2",
    "IndentBlanklineIndent3",
    "IndentBlanklineIndent4",
    "IndentBlanklineIndent5",
    "IndentBlanklineIndent6",
  },
  filetype_exclude = {
    "help",
    "startify",
    "dashboard",
    "nv",
    "packer",
    "neogitstatus",
    "NvimTree",
    "Trouble",
    "alpha",
    "lir",
    "Outline",
    "spectre_panel",
    "toggleterm",
    "qf",
    "DiffviewFiles",
    "dbui",
    "dbout",
    "nvcheatsheet",
    "nvdash",
    "mason",
    ""
  },
  use_treesitter = true,
  show_current_context = true,
}
